# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170627_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='questions.Project_Member', to='questions.Member'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
