# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20170627_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Status'),
        ),
    ]
